import React from 'react';
import QuizRenderer from '../../../components/QuizRenderer.jsx';

export default function QuizContent() {
    const questions = [
        {
            text: "What is a Helm Chart?",
            options: [
                "A visual dashboard for K8s logs.",
                "A collection of files that describe a related set of Kubernetes resources.",
                "A strict security policy enforcer.",
                "A command-line tool built into kubectl."
            ],
            correctIndex: 1,
            explanation: "A Helm Chart is the packaging format used by Helm. It packages everything needed to run an application, tool, or service inside of a Kubernetes cluster into a single directory structure."
        },
        {
            text: "In a traditional Helm chart directory, which file is used to store the default configuration values?",
            options: [
                "Chart.yaml",
                "config.yaml",
                "values.yaml",
                "templates/default.yaml"
            ],
            correctIndex: 2,
            explanation: "The `values.yaml` file is the heart of chart configuration. It provides the default variables (like image tags, replicas, port numbers) that are rendered into the templates."
        },
        {
            text: "Which command installs a Helm chart named 'my-chart' from a local directory?",
            options: [
                "helm create my-chart",
                "helm package my-chart",
                "helm install my-release-name ./my-chart",
                "helm publish my-chart"
            ],
            correctIndex: 2,
            explanation: "`helm install [RELEASE_NAME] [CHART_PATH]` installs the chart. The release name is the instance identifier Helm uses to track that specific installation."
        },
        {
            text: "What does the 'helm upgrade' command do?",
            options: [
                "It upgrades the Helm CLI binary to the latest version on your computer.",
                "It upgrades the Kubernetes API server.",
                "It updates a running Helm release with a new version of a chart, or with new configuration values.",
                "It forces all Pods to restart."
            ],
            correctIndex: 2,
            explanation: "When you change your `values.yaml` or get a newer version of a chart, you use `helm upgrade [RELEASE_NAME] [CHART_PATH_OR_REPO]` to apply the changes to your live cluster."
        },
        {
            text: "If a Helm upgrade fails or introduces bugs in production, what is the best way to revert?",
            options: [
                "Delete all the pods manually and hope they recreate correctly.",
                "Use `helm rollback [RELEASE_NAME] [REVISION]` to instantly revert to a previously known good state.",
                "Uninstall the release and reinstall it from scratch.",
                "Wait for the cluster to self-heal."
            ],
            correctIndex: 1,
            explanation: "Helm tracks every installation and upgrade as a 'revision'. `helm rollback` allows you to immediately revert the cluster state back to the exact manifests of an older revision."
        },
        {
            text: "Which templating language is natively built-in and used by Helm templates?",
            options: [
                "Jinja2",
                "Go Templates (text/template)",
                "Mustache",
                "Handlebars"
            ],
            correctIndex: 1,
            explanation: "Helm is written in Go, and it natively utilizes the Go `text/template` language (supplemented with Sprig functions) to parse and render YAML templates."
        },
        {
            text: "How is Kustomize conceptually different from Helm?",
            options: [
                "Kustomize uses a templating engine; Helm uses patches.",
                "Kustomize has a package registry (Chart Museum); Helm does not.",
                "Kustomize is built into `kubectl` and uses overlay patching instead of templating engines.",
                "They are exactly the same tool just run by different commands."
            ],
            correctIndex: 2,
            explanation: "Helm passes variables into Go templates. Kustomize (invoked via `kubectl apply -k`) takes an existing complete YAML file (`base`) and applies strategic merge patches (`overlays`) on top of it without using any templates."
        },
        {
            text: "What does `helm get notes [RELEASE_NAME]` output?",
            options: [
                "The history of who installed the release.",
                "The text generated by the `templates/NOTES.txt` file, typically providing post-installation instructions like how to get a password or URL.",
                "A sticky note added by cluster administrators.",
                "The raw YAML files deployed to the server."
            ],
            correctIndex: 1,
            explanation: "Chart authors provide a `NOTES.txt` file that renders instructions tailored to the user's configuration, displayed immediately after a successful install or upgrade."
        },
        {
            text: "What is a Helm 'Repository'?",
            options: [
                "A GitHub repository holding source code.",
                "An HTTP server that houses an `index.yaml` file and packaged charts (`.tgz`), acting like an 'app store' for Kubernetes.",
                "A local filesystem directory holding `values.yaml`.",
                "A database where etcd stores running applications."
            ],
            correctIndex: 1,
            explanation: "Just like APT or YUM repositories, Helm repositories host packaged charts. You add them via `helm repo add` and install pre-built software (like Redis or NGINX) directly from them."
        },
        {
            text: "If you want to view the raw, rendered Kubernetes YAML generated by a Helm chart without actually installing it into the cluster, which command should you use?",
            options: [
                "helm show yaml my-release",
                "helm template my-chart",
                "helm fetch my-chart",
                "helm test my-chart"
            ],
            correctIndex: 1,
            explanation: "`helm template` renders the chart templates locally and prints the resulting YAML to standard output. This is vital for debugging or feeding the manifests into other tools (like Kustomize or ArgoCD)."
        }
    ];
    return <QuizRenderer title="Helm & Package Management Quiz" questions={questions} nextModuleUrl="/learn" />;
}
